// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyForum.Data.MyForum
{
    public partial class Comments
    {
        public int Cid { get; set; }
        public int Pid { get; set; }
        public DateTime? Date { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }

        public virtual Posts PidNavigation { get; set; }
    }
}