// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyForum.Data.MyForum
{
    public partial class Posts
    {
        public Posts()
        {
            Comments = new HashSet<Comments>();
        }

        public int Pid { get; set; }
        public DateTime? Date { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<Comments> Comments { get; set; }
    }
}